import Head from "next/head";
import Script from "next/script";
import React from "react";
import BackToTop from "../../components/BackToTop";
import Breadcrum from "../../components/PortfolioDetails/Breadcrum";
import Footer from "../../components/Footer";
import Header from "../../components/PortfolioDetails/Header";
import PortfolioDetails from "../../components/PortfolioDetails/PortfolioDetails";
import Preloader from "../../components/Preloader";
import TopBar from "../../components/PortfolioDetails/TopBar";

function index() {
  return (
    <div>
      {/* <Script
        src="assets/vendor/aos/aos.js"
        strategy="afterInteractive"
        onError={(e) => {
          console.error("Script failed to load", e);
        }}
      />
      <Script
        src="assets/vendor/bootstrap/js/bootstrap.bundle.min.js"
        strategy="afterInteractive"
        onError={(e) => {
          console.error("Script failed to load", e);
        }}
      />
      <Script
        src="assets/vendor/glightbox/js/glightbox.min.js"
        strategy="afterInteractive"
        onError={(e) => {
          console.error("Script failed to load", e);
        }}
      />
      <Script
        src="assets/vendor/isotope-layout/isotope.pkgd.min.js"
        strategy="afterInteractive"
        onError={(e) => {
          console.error("Script failed to load", e);
        }}
      />
      <Script
        src="assets/vendor/swiper/swiper-bundle.min.js"
        strategy="afterInteractive"
        onError={(e) => {
          console.error("Script failed to load", e);
        }}
      />
      <Script
        src="assets/vendor/php-email-form/validate.js"
        strategy="afterInteractive"
        onError={(e) => {
          console.error("Script failed to load", e);
        }}
      />
      <Script
        src="assets/js/main.js"
        strategy="afterInteractive"
        onError={(e) => {
          console.error("Script failed to load", e);
        }}
      /> */}
      <Head>
        <title>one stop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopBar />
      <Header />
      <main id="main">
        <Breadcrum />
        <PortfolioDetails />
      </main>
      <Footer />
      <Preloader />
      <BackToTop />
    </div>
  );
}

export default index;
