import Head from "next/head";
import Script from "next/script";
import AboutUsSection from "../components/AboutUsSection";
import ClientsSection from "../components/ClientsSection";
import ContactUs from "../components/ContactUs";
import CTASection from "../components/CTASection";
import FAQSection from "../components/FAQSection";
import Footer from "../components/Footer";
import Header from "../components/Header";
import HeroSection from "../components/HeroSection";
import IconBoxesSection from "../components/IconBoxesSection";
import PortfolioSection from "../components/PortfolioSection";
import Preloader from "../components/Preloader";
import PricingSection from "../components/PricingSection";
import ServicesSection from "../components/ServicesSection";
import TeamSection from "../components/TeamSection";
import TopBar from "../components/TopBar";
import WhyUsSection from "../components/WhyUsSection";

export default function Home() {
  return (
    <div>
      <Script
        src="assets/vendor/aos/aos.js"
        strategy="afterInteractive"
        onError={(e) => {
          console.error("Script failed to load", e);
        }}
      />
      <Script
        src="assets/vendor/bootstrap/js/bootstrap.bundle.min.js"
        strategy="afterInteractive"
        onError={(e) => {
          console.error("Script failed to load", e);
        }}
      />
      <Script
        src="assets/vendor/glightbox/js/glightbox.min.js"
        strategy="afterInteractive"
        onError={(e) => {
          console.error("Script failed to load", e);
        }}
      />
      <Script
        src="assets/vendor/isotope-layout/isotope.pkgd.min.js"
        strategy="afterInteractive"
        onError={(e) => {
          console.error("Script failed to load", e);
        }}
      />
      <Script
        src="assets/vendor/swiper/swiper-bundle.min.js"
        strategy="afterInteractive"
        onError={(e) => {
          console.error("Script failed to load", e);
        }}
      />
      <Script
        src="assets/vendor/php-email-form/validate.js"
        strategy="afterInteractive"
        onError={(e) => {
          console.error("Script failed to load", e);
        }}
      />
      <Script
        src="assets/js/main.js"
        strategy="afterInteractive"
        onError={(e) => {
          console.error("Script failed to load", e);
        }}
      />
      <Head>
        <title>one stop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <TopBar />
      <Header />
      <HeroSection />
      <main id="main">
        <IconBoxesSection />
        <AboutUsSection />
        <ClientsSection />
        <WhyUsSection />
        <ServicesSection />
        {/* <CTASection /> */}
        <PortfolioSection />
        <TeamSection />
        <PricingSection />
        <FAQSection />
        <ContactUs />
      </main>
      <Footer />
      <Preloader />
      <a
        href="#"
        className="back-to-top d-flex align-items-center justify-content-center"
      >
        <i className="bi bi-arrow-up-short"></i>
      </a>
    </div>
  );
}
